### ISSUE TITLE
External configuration file

### ISSUE THREAD

**Issue by ghost** [meenie/8bit.js#13]
I created an experimental branch with support for an [external configuration file](https://github.com/ksd5/8bit.js/tree/ext-config/src). I suck at JavaScript though, so I don't know if this functionality even works at this point (and I haven't tested it yet.)

What do you think of it?

**Comment by brigand** [comment]
In what situation would this be useful?  Why would you want to change any of these settings?

**Comment by ghost** [comment]
I had detailed the reasons in Issue #10. Basically, it would be easier to implement alternative tuning systems and time signatures if these settings were kept in an external file, so the library itself wouldn't have to be modified.

**Comment by meenie** [comment]
I can see the benifit of having the ability to change pitches/rhythms/etc but the implementation you are using can cause a lot issues due to the library looking for generic variables `notes`, `pitches`, `waveforms`, etc in the global namespace.  If someone using 8bit.js in their library accidentally uses one of those with an out of context value, it will make 8bit.js stop working.  What would be best is create a public method inside of 8bit.js called `config()` that you can use to overwrite the configuration of some of those variables.  Have another go at it :).

**Comment by ghost** [comment]
I'm trying to avoid using method calls to set the variables. I favored an external configuration file because it could be hosted centrally if it happened to be a set of options that represented a musical system unlikely to change (such as existing and established tonal systems).

In the worst case, I will implement a `config()` method or similar method-based configuration functionality. However, would using a JSON-based settings file be a better way to go about it than a JS-variable-based settings file?

**Comment by meenie** [comment]
You could make it a static method where you only have to set it once and can create numerous new `EightBit()` objects using those settings that were set only once.

**Comment by meenie** [comment]
And about having the settings in a JSON object, I think that would be best :).

**Comment by brigand** [comment]
If you make it static, then you can't have multiple `EightBit` objects with different settings.  If you make it an instance property, you can have them all be the same, or have some be different.  If you define it in the prototype it can be overridden once for everything, or individually.  

Set it for all:

``` javascript
EightBit.prototype.pitches = { ... }
```

Set it for one:

``` javascript
var a = new EightBit()
a.pitches = { ... }
```

Set a default, and then override it on one

``` javascript
EightBit.prototype.pitches = { ... }
var a = new EightBit() // use the changed prototype
var b = new EightBit() // use the changed prototype
var c = new EightBit()
c.pitches = { ... } // override it just for c
```

---

Another option is to have it be a constructor argument, in addition to the above.

``` javascript
a = new EightBit({ pitches: myCustomPitches });
```

**Comment by meenie** [comment]
Good point @brigand.  I'm in favour of the constructor argument myself, it's much cleaner looking.  What do you think?

**Comment by ghost** [comment]
[I implemented the external config file as a JavaScript file with a single JSON object, containing all the settings.](https://github.com/ksd5/8bit.js/tree/ext-config/src) The library checks to see if it's defined. If it isn't, it falls back to the defaults. Otherwise, it sets the internal variables as equal to the members of the JSON object.

This implementation reduces the problem of too many global variables, and it has the benefit of allowing cross-site requests. (I was trying to use AJAX before, until I realized that cross-site requests wouldn't work.) I made the object name unique enough that the chance of someone accidentally overwriting it would remain at a minimum.

---

I like the constructor argument; it's very straightforward. I will try implementing that next.

**Comment by meenie** [comment]
I'm sorry but I still don't like the configuration like this. I'm actually going to refactor the library over the next couple of days to make it more modular and plugin oriented. I'll creating an issue outlining what I'm going to do so stay tuned :-).

**Comment by meenie** [comment]
I have completed by rewrite and configuration is done with the help of "packs". The new library is located here: https://github.com/meenie/band.js
